services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./docker/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./docker/certbot/www/:/var/www/certbot/:ro
    env_file:
      - .env

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/:rw
      - ./docker/certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
