services:

  minio:
    image: minio/minio
    volumes:
      - ./docker/minio:/minio_files
    env_file:
      - .env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  create_buckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      mc config host add neuro-crm-minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
      mc mb --quiet neuro-crm-minio/files;
      mc policy set none neuro-crm-minio/files;
      "
