name: Check Lint Migrations Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_migrations_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: yezz123/setup-uv@v4
        with:
          uv-venv: ".venv"

      - uses: cardinalby/export-env-action@v1
        with:
          envFile: '.env.example'
          expand: 'true'

      - name: Debug
        run: |
          echo ${{ github.event.repository.name }}

      - name: Install Requirements Dev
        run: make install_requirements_dev

      - name: Check Lint
        run: make check_lint

      - name: Check Migrations
        run: make check_migrations

      - name: Run Tests
        run: make tests

      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
