name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_migrations_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install_dependencies
        run: pip install -r requirements_dev.txt

      - name: check_lint
        run: make check_lint

      - name: check_migrations
        run: make check_migrations

      - name: tests
        run: make tests
