name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  check_lint_migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: check_lint
        run: make check_lint

      - name: check_migrations
        run: make check_migrations


